In [1]:
import pandas as pd
import numpy as np

In [2]:
import sys
sys.path.append('/Users/bengikoseoglu/anaconda2/pkgs')
sys.path.append('/Users/bengikoseoglu/anaconda2/pckgs')
sys.path.append('/Users/bengikoseoglu')
sys.path.append('/Library/Python/2.7/site-packages/')
sys.path

['',
 '/Users/bengikoseoglu/anaconda2/lib/python27.zip',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/plat-darwin',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/plat-mac',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/lib-tk',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/lib-old',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/lib-dynload',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/aeosa',
 '/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/IPython/extensions',
 '/Users/bengikoseoglu/.ipython',
 '/Users/bengikoseoglu/anaconda2/pkgs',
 '/Users/bengikoseoglu/anaconda2/pckgs',
 '/Users/bengikoseoglu',
 '/Library/Python/2.7/site-packages/']

In [3]:
import pandas as pd
import numpy as np
import datetime
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import *
import plotly.plotly as py
import plotly
import plotly.graph_objs as go
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [4]:
df=pd.read_excel('cameras_400_3_nocamera.xlsx')

In [5]:
df.shape

(418, 19)

In [6]:
df=df.rename(columns={'Leaf Node':'Leaf_Node'})

In [7]:
df.head()

,ID,name,Leaf_Node,priceCurrency,price,brand,itemCondition,availability,Description,image,gtin12,gtin13,gtin14,gtin8,ratingValue,bestRating,reviewCount,Unnamed: 17,Good Examples
0,jessops-f2dd233dd6100c900432fd2902df8cde,Nikon Coolpix P900 Digital Camera,Bridge Cameras,GBP,479,Nikon,NaN,True,NaN,https://i.jessops.com/images/home/homepage/100...,NaN,NaN,NaN,2018-09-08,10,162.0,NaN,NaN,NaN
1,jessops-ff2be7ba459709194635812c728a17fd,Canon EOS 750D Digital SLR with 18-55mm IS STM...,DSLR,GBP,539,Canon,NaN,True,NaN,https://i.jessops.com/images/home/homepage/100...,NaN,NaN,NaN,2018-02-09,10,361.0,NaN,NaN,NaN
2,jessops-acfa4e6fdc0962be2da5bc1ed8d44357,Canon EOS 5D Mark IV Digital SLR Body,DSLR,GBP,3249,Canon,NaN,True,NaN,https://i.jessops.com/images/home/homepage/100...,NaN,NaN,NaN,NaT,2018-07-09 00:00:00,10.0,25.0,NaN,NaN
3,jessops-cabb446087d8428bfa741078869439b8,Canon EOS 7D Mark II Digital SLR Body,DSLR,GBP,1349,Canon,NaN,True,NaN,https://i.jessops.com/images/home/homepage/100...,NaN,NaN,NaN,NaT,2018-04-09 00:00:00,10.0,268.0,NaN,NaN
4,jessops-8c6e0672aa9297ee8ff4d95fa5e2edc0,Sony A6000 Mirrorless Camera in Black with 16-...,Full Frame Mirrorless Camera,GBP,449,Sony,NaN,True,NaN,https://i.jessops.com/images/home/homepage/100...,NaN,NaN,NaN,NaT,9.0,10.0,107.0,NaN,NaN

In [8]:
df.shape

(418, 19)

In [9]:
df.ID.nunique()

416

In [10]:
#IN (1, 3, 99)


q = """
SELECT DISTINCT *, (CASE WHEN Leaf_Node IN ('360 Degree Cameras','Common Use Video Cameras','Non 360 Degree Cameras',
'Professional Video Cameras','Drone') THEN 'Cam Corders' WHEN Leaf_Node IN ('Not Camera') THEN 'Not Camera' ELSE 'Photo Devices' END) AS parent_node_1, 
(CASE WHEN Leaf_Node IN ('360 Degree Cameras','Non 360 Degree Cameras','Drone') THEN 'Action Cameras' 
WHEN Leaf_Node IN ('Bridge Cameras','Digital Compact Cameras','Instant') THEN 'Point & Shoot Cameras' 
WHEN Leaf_Node IN ('Common Use Video Cameras','Professional Video Cameras') THEN 'Traditional Video Cameras' 
WHEN Leaf_Node IN ('DSLR') THEN 'DSLR' 
WHEN Leaf_Node IN ('Not Camera') THEN 'Not Camera'
WHEN Leaf_Node IN ('Full Frame Mirrorless Camera','NonFullFrameMirrorlessCamera') THEN 'Mirrorless Cameras' 
ELSE 'NO CATEGORY'
END) AS parent_node_2
FROM df
"""
df = pysqldf(q)

In [11]:
df.shape

(416, 21)

In [12]:
df.Leaf_Node.unique()

array([u'Bridge Cameras', u'DSLR', u'Full Frame Mirrorless Camera',
       u'NonFullFrameMirrorlessCamera', u'Digital Compact Cameras',
       u'Common Use Video Cameras', u'Instant', u'360 Degree Cameras',
       u'Non 360 Degree Cameras', u'Professional Video Cameras', u'Drone',
       u'Not Camera'], dtype=object)

In [13]:
df.head()

,ID,name,Leaf_Node,priceCurrency,price,brand,itemCondition,availability,Description,image,...,gtin13,gtin14,gtin8,ratingValue,bestRating,reviewCount,Unnamed: 17,Good Examples,parent_node_1,parent_node_2
0,jessops-f2dd233dd6100c900432fd2902df8cde,Nikon Coolpix P900 Digital Camera,Bridge Cameras,GBP,479,Nikon,None,True,None,https://i.jessops.com/images/home/homepage/100...,...,NaN,None,2018-09-08 00:00:00.000000,10,162.0,NaN,None,None,Photo Devices,Point & Shoot Cameras
1,jessops-ff2be7ba459709194635812c728a17fd,Canon EOS 750D Digital SLR with 18-55mm IS STM...,DSLR,GBP,539,Canon,None,True,None,https://i.jessops.com/images/home/homepage/100...,...,NaN,None,2018-02-09 00:00:00.000000,10,361.0,NaN,None,None,Photo Devices,DSLR
2,jessops-acfa4e6fdc0962be2da5bc1ed8d44357,Canon EOS 5D Mark IV Digital SLR Body,DSLR,GBP,3249,Canon,None,True,None,https://i.jessops.com/images/home/homepage/100...,...,NaN,None,None,2018-07-09 00:00:00,10.0,25.0,None,None,Photo Devices,DSLR
3,jessops-cabb446087d8428bfa741078869439b8,Canon EOS 7D Mark II Digital SLR Body,DSLR,GBP,1349,Canon,None,True,None,https://i.jessops.com/images/home/homepage/100...,...,NaN,None,None,2018-04-09 00:00:00,10.0,268.0,None,None,Photo Devices,DSLR
4,jessops-8c6e0672aa9297ee8ff4d95fa5e2edc0,Sony A6000 Mirrorless Camera in Black with 16-...,Full Frame Mirrorless Camera,GBP,449,Sony,None,True,None,https://i.jessops.com/images/home/homepage/100...,...,NaN,None,None,9.0,10.0,107.0,None,None,Photo Devices,Mirrorless Cameras

In [14]:
#IN (1, 3, 99)


q = """
SELECT DISTINCT parent_node_1,parent_node_2,Leaf_Node, COUNT(ID)
FROM df
GROUP BY parent_node_1,parent_node_2,Leaf_Node
"""
a = pysqldf(q)
a

,parent_node_1,parent_node_2,Leaf_Node,COUNT(ID)
0,Cam Corders,Action Cameras,360 Degree Cameras,21
1,Cam Corders,Action Cameras,Drone,15
2,Cam Corders,Action Cameras,Non 360 Degree Cameras,22
3,Cam Corders,Traditional Video Cameras,Common Use Video Cameras,21
4,Cam Corders,Traditional Video Cameras,Professional Video Cameras,32
5,Not Camera,Not Camera,Not Camera,19
6,Photo Devices,DSLR,DSLR,72
7,Photo Devices,Mirrorless Cameras,Full Frame Mirrorless Camera,31
8,Photo Devices,Mirrorless Cameras,NonFullFrameMirrorlessCamera,50
9,Photo Devices,Point & Shoot Cameras,Bridge Cameras,56
10,Photo Devices,Point & Shoot Cameras,Digital Compact Cameras,58
11,Photo Devices,Point & Shoot Cameras,Instant,19

In [15]:
df.shape

(416, 21)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
corpus=df['name']

In [18]:
corpus.head()

0                    Nikon Coolpix P900 Digital Camera
1    Canon EOS 750D Digital SLR with 18-55mm IS STM...
2                Canon EOS 5D Mark IV Digital SLR Body
3                Canon EOS 7D Mark II Digital SLR Body
4    Sony A6000 Mirrorless Camera in Black with 16-...
Name: name, dtype: object

In [19]:
vectorizer = CountVectorizer()

In [20]:
vectorizer

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [21]:
matrix=vectorizer.fit_transform(corpus).todense()

In [22]:
matrix.shape #291 columns, 121 rows

(416, 875)

In [23]:
vocab=vectorizer.vocabulary_

In [24]:
len(vocab)

875

In [25]:
bags_words=pd.DataFrame(matrix, columns=sorted(vocab))

In [26]:
bags_words['ID']=df['ID']
bags_words['Parent_node_1']=df['parent_node_1']
bags_words['Parent_node_2']=df['parent_node_2']
bags_words['Leaf_Node']=df['Leaf_Node']

In [27]:
bags_words.head()

,007,012,018208021970,06581,10,100mm,101,102,105,105mm,...,zero,zink,zoom,zoomlens,zr10,zs100,ID,Parent_node_1,Parent_node_2,Leaf_Node
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,jessops-f2dd233dd6100c900432fd2902df8cde,Photo Devices,Point & Shoot Cameras,Bridge Cameras
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,jessops-ff2be7ba459709194635812c728a17fd,Photo Devices,DSLR,DSLR
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,jessops-acfa4e6fdc0962be2da5bc1ed8d44357,Photo Devices,DSLR,DSLR
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,jessops-cabb446087d8428bfa741078869439b8,Photo Devices,DSLR,DSLR
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,jessops-8c6e0672aa9297ee8ff4d95fa5e2edc0,Photo Devices,Mirrorless Cameras,Full Frame Mirrorless Camera

In [28]:
bags_words.shape

(416, 879)

In [29]:
bags_words.Parent_node_1.unique()

array([u'Photo Devices', u'Cam Corders', u'Not Camera'], dtype=object)

In [30]:
bags_words.Parent_node_2.unique()

array([u'Point & Shoot Cameras', u'DSLR', u'Mirrorless Cameras',
       u'Traditional Video Cameras', u'Action Cameras', u'Not Camera'], dtype=object)

In [31]:
bags_words.shape

(416, 879)

# Modeling

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score

def confusion_matrix_report(y_true, y_pred):
    cm, labels = confusion_matrix(y_true, y_pred), unique_labels(y_true, y_pred)
    column_width = max([len(str(x)) for x in labels] + [5])  # 5 is value length
    report = " " * column_width + " " + "{:_^{}}".format("Prediction", column_width * len(labels))+ "\n"
    report += " " * column_width + " ".join(["{:>{}}".format(label, column_width) for label in labels]) + "\n"
    for i, label1 in enumerate(labels):
        report += "{:>{}}".format(label1, column_width) + " ".join(["{:{}d}".format(cm[i, j], column_width) for j in range(len(labels))]) + "\n"
    return report
    
def analytics(y_true, y_pred):#target of the test data #predictions as 0,1 #model (knnclassifier) #data_test
    print("Confusion Matrix:")
    print(confusion_matrix_report(y_true, y_pred))
    print("Accuracy Score:")
    print(accuracy_score(y_true, y_pred))
    print()
    print("Classification Report:")
    print(classification_report(y_true, y_pred))
    #print("AUC Score:")
    #print(AUC(target_test, model, data_test))

## 1. Modeling with only Bags of Words:

# Modeling with Logistic Regression with F Classification

### Level 1

In [33]:
df_model=df[['ID','priceCurrency','price','brand']]
brand_dummies=pd.get_dummies(df_model['brand'])
pricecur_dummies=pd.get_dummies(df_model['priceCurrency'])
df_model=pd.concat([df_model,brand_dummies,pricecur_dummies],axis=1) #pd.concat([df1, df4], axis=1
bags=bags_words.copy()
model2=df_model.merge(bags,on='ID',how='inner')
model2=model2.drop(['priceCurrency','brand'],axis=1)
a=model2['price'].str.split(',', 1, expand=True)
a=a.drop([206])
a=a.astype(float)
model2['price']=a[0]
median(model2['price'].dropna())
# filling missing values with median
model2['price']=model2['price'].fillna(548)

In [34]:
model2.head()

,ID,price,360fly_x,6Ave,Air Hogs,AmazingForLess,Axess Products,Bell+Howell,BlackMagic,Blackmagic,...,zeiss,zero,zink,zoom,zoomlens,zr10,zs100,Parent_node_1,Parent_node_2,Leaf_Node
0,jessops-f2dd233dd6100c900432fd2902df8cde,479.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,Photo Devices,Point & Shoot Cameras,Bridge Cameras
1,jessops-ff2be7ba459709194635812c728a17fd,539.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,Photo Devices,DSLR,DSLR
2,jessops-acfa4e6fdc0962be2da5bc1ed8d44357,3249.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,Photo Devices,DSLR,DSLR
3,jessops-cabb446087d8428bfa741078869439b8,1349.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,Photo Devices,DSLR,DSLR
4,jessops-8c6e0672aa9297ee8ff4d95fa5e2edc0,449.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,Photo Devices,Mirrorless Cameras,Full Frame Mirrorless Camera

- Prepare all test dataset

In [35]:
import os
os.chdir('/Users/bengikoseoglu/Documents/Masters/Semester2/TeamProject/crawling/webproductminingtp-755782b3e663dffc4cf4ae55a2aadb8a79157e83/data/csv/cameras')

In [36]:
all_files=list(os.listdir(os.getcwd()))

In [37]:
i=1
a=pd.read_csv(all_files[0])
cols=list(a.columns.values)
while(i<len(all_files)):
        b=pd.read_csv(all_files[i])
        a=a.append(b)
        i=i+1

In [38]:
a.tail()

,Unnamed: 0,availability,bestRating,brand,description,gtin12,gtin13,gtin14,gtin8,id,identifier,image,itemCondition,name,price,priceCurrency,prod_cat,ratingValue,reviewCount
139,NaN,http://schema.org/InStock,NaN,Nikon,"Dive to depths of 30m, freeze in conditions do...",NaN,NaN,NaN,NaN,NaN,park-f4bd16aa906c4a7d459b28f7dfd3c6b3,https://content.parkcameras.com/5/1/images/cat...,http://schema.org/NewCondition,Nikon Coolpix W300 Waterproof Compact Camera i...,�389.00,GBP,NaN,NaN,NaN
140,NaN,http://schema.org/InStock,NaN,Canon,NaN,NaN,NaN,NaN,NaN,NaN,park-f71c5c3c1b56eeffc8cc5ef387a70195,https://content.parkcameras.com/5/1/images/cat...,http://schema.org/NewCondition,Canon PowerShot G1 X Mark II Compact Camera,�559.00,GBP,NaN,NaN,NaN
141,NaN,http://schema.org/InStock,NaN,Sony,all of the advantages of a 35mm full frame ima...,NaN,NaN,NaN,NaN,NaN,park-f79d619b325c99e8eeadd08afae53d01,https://content.parkcameras.com/5/1/images/cat...,http://schema.org/NewCondition,Sony a7 mirrorless Digital Camera Body,�799.00,GBP,NaN,NaN,NaN
142,NaN,http://schema.org/InStock,NaN,Sony,NaN,NaN,NaN,NaN,NaN,NaN,park-f7bdb5e27033955f66da446c9d235ac9,https://content.parkcameras.com/5/1/images/cat...,http://schema.org/NewCondition,Sony DSC RX1 Compact Digital Camera,"�2,125.00",GBP,NaN,NaN,NaN
143,NaN,http://schema.org/InStock,NaN,Sony,"The Sony a7S, where �S� stands for sensitivity...",NaN,NaN,NaN,NaN,NaN,park-f7dd6adb1b8089840c17d02649fad909,https://content.parkcameras.com/5/1/images/cat...,http://schema.org/NewCondition,Sony a7S Mirrorless Camera Body,"�1,509.00",GBP,NaN,NaN,NaN

In [39]:
a[a['name'].isnull()] #there are some missing values, we will drop these values

,Unnamed: 0,availability,bestRating,brand,description,gtin12,gtin13,gtin14,gtin8,id,identifier,image,itemCondition,name,price,priceCurrency,prod_cat,ratingValue,reviewCount
327,327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-2895c568a524764f5abb15037406d6e6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-66c4367a49aaa18a9ff8b90806fe6b9e,NaN,NaN,NaN,1039,USD,NaN,NaN,NaN
3830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-790d954d90c89857f3198b0fa4740279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-96db832be3958181c0b420cf2635894d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-ac6247adf2feeed694ac6da31094d8b0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-b17b2bae985926ed50e6695cc4573b67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-bb1a08710e06e27f8f2203fc030c872a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,newegg-e10554f42c38e4b3e8efe9a35f594f8c,NaN,NaN,NaN,185,USD,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bestbuy-15f44e6dba872cefaf6f732a5e7c63a3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bestbuy-46225d684ce7406028cf13a8c4e6ede2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bestbuy-75dc708109710d07f5e60b0bf8471382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bestbuy-d54cb15e32ba903d187f4d58c3b4a382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
977,977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
979,979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
a.shape

(23478, 19)

In [41]:
a2=a.dropna(subset=['name']) #drop missing values in name, rest can be filled.
a2.shape

(22979, 19)

In [42]:
a2=a2.reset_index().drop('index',axis=1)

In [43]:
corpus=a2['name']
vectorizer = CountVectorizer(encoding='latin-1')
matrix=vectorizer.fit_transform(corpus).todense()
vocab=vectorizer.vocabulary_ 
bags_words=pd.DataFrame(matrix, columns=sorted(vocab))

In [44]:
bags_words.head()

,00,00000018,00000023,00000130,000087,0001,000119,00013,000133,000147,...,zs60s,zs7,zs70,zs70k,zs70s,zs8,zstrv,zuiko,zx,zx5
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Adding brand, price, price currency etc.

In [45]:
df_model=a2[['priceCurrency','price','brand']]

In [46]:
df_model['brand'].value_counts().keys() #most common brand now lets fill missingness in brand with Canon

Index([u'Canon', u'Sony', u'Nikon', u'Panasonic', u'Fujifilm', u'CANON',
       u'SONY', u'NIKON', u'Olympus', u'FUJIFILM',
       ...
       u'Kalt', u'DxO', u'KroO', u'Swann Communications USA',
       u'AVer Information', u'Stealth Cam', u'DXG', u'Konig', u'Bushnell',
       u'BSA Optics'],
      dtype='object', length=427)

In [47]:
df_model['brand']=df_model['brand'].fillna('Canon')

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [48]:
df_model[df_model['price'].isnull()].shape

(3897, 3)

In [49]:
df_model['price']

0           799.99
1           699.99
2          1099.95
3             1295
4           399.99
5          2796.95
6           899.99
7           349.99
8           396.95
9           699.99
10          499.99
11            1499
12          746.95
13         1599.95
14         2296.95
15         1296.95
16          279.99
17             499
18          329.99
19         6499.95
20            1999
21         1599.99
22            3899
23          349.99
24          899.99
25         2699.99
26          599.99
27          249.99
28          399.99
29          249.97
           ...
22949      �799.00
22950    �1,299.00
22951      �499.00
22952      �499.00
22953      �379.00
22954      �389.00
22955    �3,450.00
22956      �229.00
22957      �679.00
22958    �1,199.00
22959    �1,399.00
22960       �18.99
22961      �249.00
22962      �779.00
22963      �949.00
22964        �8.99
22965       �99.00
22966      �429.00
22967      �449.00
22968    �2,399.00
22969      �199.97
22970    �1,729.00
22971      �899.00
22972      �157.97
22973    �3,600.00
22974      �389.00
22975      �559.00
22976      �799.00
22977    �2,125.00
22978    �1,509.00
Name: price, Length: 22979, dtype: object

In [50]:
str(df_model['price'].loc[22973])[0]

'\xa3'

In [51]:
i=0
n=df_model.shape[0]
price=[]
while(i<n):
    ch=str(df_model['price'].loc[i])[0]
    if(ch=='1' or ch=='2'or ch=='3'or ch=='4'or ch=='5'or ch=='6'or ch=='7'or ch=='8'or ch=='9' or ch=='0' or ch=='n'):
        price.append(df_model['price'].loc[i])
    else:
        price.append(df_model['price'].loc[i][1:])
    i=i+1

In [52]:
price[22978]

'1,509.00'

In [53]:
price2=[str(x).replace(',', '') for x in price]

In [54]:
price_df=pd.DataFrame(price2)

In [55]:
price_df['price_f']=price_df[0].astype(float)

In [56]:
price_df.head()

         0  price_f
0   799.99   799.99
1   699.99   699.99
2  1099.95  1099.95
3   1295.0  1295.00
4   399.99   399.99

In [57]:
price_df['price_f'].median()

487.995

In [58]:
price_df['price_f']=price_df['price_f'].fillna(487.995)

In [59]:
df_model.price=price_df['price_f']

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py:3110: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [60]:
df_model.head()

  priceCurrency    price              brand
0           USD   799.99          Panasonic
1           USD   699.99               Sony
2           USD  1099.95             Pentax
3           USD  1295.00  Blackmagic Design
4           USD   399.99            Olympus

In [61]:
brand_dummies=pd.get_dummies(df_model['brand'])
pricecur_dummies=pd.get_dummies(df_model['priceCurrency'])

In [62]:
df_model=pd.concat([df_model,brand_dummies,pricecur_dummies],axis=1)
bags=bags_words.copy()

In [63]:
df_model.shape

(22979, 433)

In [64]:
bags_words.shape

(22979, 9465)

In [65]:
df_model.head() #had model, brand, price currency as dummies

,priceCurrency,price,brand,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus',...,buydirect-1483C002,default,eCostConnection,econoLED,iOn America,iPM,lESHP,GBP,USD,pound
0,USD,799.99,Panasonic,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,USD,699.99,Sony,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,USD,1099.95,Pentax,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,USD,1295.00,Blackmagic Design,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,USD,399.99,Olympus,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [66]:
df_model.shape

(22979, 433)

In [67]:
bags_words.head() #has the name

,00,00000018,00000023,00000130,000087,0001,000119,00013,000133,000147,...,zs60s,zs7,zs70,zs70k,zs70s,zs8,zstrv,zuiko,zx,zx5
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
bags_words=bags_words.drop(['price'],axis=1)

In [69]:
bags_words.shape

(22979, 9464)

In [70]:
model3=pd.concat([df_model,bags_words],axis=1)

In [71]:
model3.head()

,priceCurrency,price,brand,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus',...,zs60s,zs7,zs70,zs70k,zs70s,zs8,zstrv,zuiko,zx,zx5
0,USD,799.99,Panasonic,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,USD,699.99,Sony,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,USD,1099.95,Pentax,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,USD,1295.00,Blackmagic Design,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,USD,399.99,Olympus,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
model3.shape

(22979, 9897)

In [73]:
model3=model3.drop(['priceCurrency','brand'],axis=1)

In [74]:
model3.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,zs60s,zs7,zs70,zs70k,zs70s,zs8,zstrv,zuiko,zx,zx5
0,799.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,699.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1099.95,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1295.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,399.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
model3_cols=list(model3.columns.values)

In [76]:
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score

def confusion_matrix_report(y_true, y_pred):
    cm, labels = confusion_matrix(y_true, y_pred), unique_labels(y_true, y_pred)
    column_width = max([len(str(x)) for x in labels] + [5])  # 5 is value length
    report = " " * column_width + " " + "{:_^{}}".format("Prediction", column_width * len(labels))+ "\n"
    report += " " * column_width + " ".join(["{:>{}}".format(label, column_width) for label in labels]) + "\n"
    for i, label1 in enumerate(labels):
        report += "{:>{}}".format(label1, column_width) + " ".join(["{:{}d}".format(cm[i, j], column_width) for j in range(len(labels))]) + "\n"
    return report
    
def analytics(y_true, y_pred):#target of the test data #predictions as 0,1 #model (knnclassifier) #data_test
    print("Confusion Matrix:")
    print(confusion_matrix_report(y_true, y_pred))
    print("Accuracy Score:")
    print(accuracy_score(y_true, y_pred))
    print()
    print("Classification Report:")
    print(classification_report(y_true, y_pred))
    #print("AUC Score:")
    #print(AUC(target_test, model, data_test))

### Level 1

In [77]:
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

In [78]:
X_level1=model2.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node'],axis=1)
y_level1=model2['Parent_node_1']

In [79]:
X_level1.head()

,price,360fly_x,6Ave,Air Hogs,AmazingForLess,Axess Products,Bell+Howell,BlackMagic,Blackmagic,Blackmagic Design,...,yuneec,z150,z212,zeiss,zero,zink,zoom,zoomlens,zr10,zs100
0,479.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,539.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3249.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1349.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,449.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [80]:
X_level1.shape

(416, 953)

In [81]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif, mutual_info_classif
import numpy as np # linear algebra
import matplotlib.pyplot as plt
import seaborn as sbn
import math

In [82]:
#F_CLASSIF
feature_names = list(X_level1.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level1, y_level1)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

In [83]:
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV
X_level1=X_level1[new_features_f]

param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level1, y_level1)
print(clf.best_params_)

{'penalty': 'l1', 'C': 10}

In [84]:
new_features_f2=['blackmagic' if x=='BlackMagic' else x for x in new_features_f]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X_level1, y_level1, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l1', C= 10)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
              ______________Prediction_______________
               Cam Corders    Not Camera Photo Devices
  Cam Corders           24             0             3
   Not Camera            1             3             5
Photo Devices            2             0            87

Accuracy Score:
0.912
()
Classification Report:
               precision    recall  f1-score   support

  Cam Corders       0.89      0.89      0.89        27
   Not Camera       1.00      0.33      0.50         9
Photo Devices       0.92      0.98      0.95        89

  avg / total       0.92      0.91      0.90       125

In [86]:
X_all=model3[new_features_f2]
target_prediction = logreg.predict(X_all)
model3['prediction_level1']=target_prediction

In [87]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l1', C= 10)
target_prediction = cross_val_predict(logreg, X_level1, y_level1, cv=cv)
model2['prediction_level1']=target_prediction

### Level 2

#### Camcorders

In [88]:
level2_train=model2[model2['Parent_node_1']=='Cam Corders'] #this includes wrongly assigned instances

In [89]:
X_level2=level2_train.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1'],axis=1)
y_level2=level2_train['Parent_node_2']

In [90]:
#F_CLASSIF
feature_names = list(X_level2.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level2, y_level2)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  2   6   7  10  12  13  19  20  21  22  23  24  26  27  28  29  30  32
  34  36  38  39  40  41  43  44  46  49  50  54  56  57  58  59  60  63
  64  66  68  69  70  78  79  80  81  82  83  85  87  90  91  92  94  95
  96  97  98  99 100 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 119 120 121 122 123 124 126 127 130 131 133 134 136 137 138 139
 140 141 142 143 146 147 148 149 150 152 153 154 156 157 158 160 161 167
 168 169 171 173 174 175 176 177 178 180 181 182 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199 200 201 202 203 205 206 208 209 210
 211 213 214 215 216 217 218 219 220 221 223 224 226 227 228 230 231 232
 233 234 235 236 237 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 260 264 266 267 268 270 271 277 279 283 284 285 292 293
 294 295 296 298 299 302 303 309 311 312 314 315 316 319 323 327 329 331
 334 335 337 342 344 345 346 351 354 355 356 357 362 363 364 365 366 367
 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 388 391 397
 398 401 402 403 404 406 407 410 413 414 415 417 418 421 422 424 425 426
 433 434 435 436 438 441 442 445 447 452 454 455 457 462 465 466 467 468
 469 471 475 476 478 479 480 481 482 483 484 485 486 487 488 489 490 491
 493 494 495 496 497 498 499 500 502 503 504 505 506 507 511 512 516 520
 521 523 524 532 538 546 550 551 553 555 556 557 558 559 561 563 564 565
 566 567 568 570 573 575 576 578 579 582 583 584 585 589 592 593 596 597
 600 602 605 607 609 611 615 616 617 618 619 620 621 624 625 626 627 628
 631 632 634 636 640 641 642 643 644 646 647 649 652 655 656 658 659 660
 662 663 664 667 668 671 677 679 682 684 691 692 693 694 695 696 697 700
 702 703 707 708 709 710 712 714 715 716 717 718 719 721 728 729 731 732
 733 737 738 739 740 743 747 748 751 753 757 759 761 763 764 765 766 767
 768 769 770 772 776 777 778 779 780 785 786 787 788 789 790 792 795 796
 797 798 799 800 802 803 804 805 806 811 814 815 817 821 824 826 832 833
 834 835 837 838 839 840 841 843 845 847 848 850 853 854 855 857 858 859
 860 862 863 864 867 868 871 872 873 874 876 877 878 881 882 886 887 894
 895 896 897 898 905 908 910 911 913 914 916 917 918 924 931 934 935 941
 945 946 947 948 951 952] are constant.

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning:

invalid value encountered in divide

In [91]:
X_level2=X_level2[new_features_f]

param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level2, y_level2)
print(clf.best_params_)

{'penalty': 'l2', 'C': 1000}

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X_level2, y_level2, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 10000)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                          ____________________Prediction____________________
                                    Action Cameras Traditional Video Cameras
           Action Cameras                       18                         0
Traditional Video Cameras                        1                        15

Accuracy Score:
0.970588235294
()
Classification Report:
                           precision    recall  f1-score   support

           Action Cameras       0.95      1.00      0.97        18
Traditional Video Cameras       1.00      0.94      0.97        16

              avg / total       0.97      0.97      0.97        34

In [93]:
X_train.shape

(77, 100)

In [94]:
X_all.shape

(22979, 100)

In [95]:
X_all=model3[new_features_f]
target_prediction = logreg.predict(X_all)
model3['prediction_level2_camcorder']=target_prediction
model3['proba_level2_camcorder_trad']=logreg.predict_proba(X_all)[:,1]
model3['proba_level2_camcorder_action']=logreg.predict_proba(X_all)[:,0]

In [96]:
model3.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,zs70s,zs8,zstrv,zuiko,zx,zx5,prediction_level1,prediction_level2_camcorder,proba_level2_camcorder_trad,proba_level2_camcorder_action
0,799.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,Traditional Video Cameras,0.864902,0.135098
1,699.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Cam Corders,Traditional Video Cameras,0.935722,0.064278
2,1099.95,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,Traditional Video Cameras,0.548473,0.451527
3,1295.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Cam Corders,Traditional Video Cameras,0.988314,0.011686
4,399.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,Action Cameras,0.044195,0.955805

In [97]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1000)
target_prediction = cross_val_predict(logreg, X_level2, y_level2, cv=cv)
level2_train['prediction_level2']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

##### 1. Traditional Video Cameras

In [98]:
#prediction_level2_camcorders
level3_train=level2_train[level2_train['Parent_node_2']=='Traditional Video Cameras']

In [99]:
X_level3=level3_train.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1','prediction_level2'],axis=1)
y_level3=level3_train['Leaf_Node']

In [100]:
#F_CLASSIF
feature_names = list(X_level3.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level3, y_level3)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  1   2   3   4   5   6   7  10  12  13  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  49  50  53  54  55  56  57  58  59  60  61
  62  63  64  65  66  68  69  70  71  73  74  75  78  79  80  81  82  83
  84  85  87  90  91  92  94  95  96  97  98  99 100 101 102 103 104 105
 106 107 108 109 110 111 112 113 114 115 116 117 119 120 121 122 123 124
 126 127 128 129 130 131 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 160 161 165 167
 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 205
 206 208 209 210 211 213 214 215 216 217 218 219 220 221 223 224 225 226
 227 228 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245
 246 247 248 249 250 251 252 253 254 255 256 257 259 260 261 262 263 264
 265 266 267 268 269 270 271 272 273 276 277 278 279 280 283 284 285 290
 291 292 293 294 295 296 298 299 300 302 303 305 306 309 311 312 314 315
 316 318 319 321 322 323 324 327 329 331 333 334 335 337 339 340 341 342
 344 345 346 347 350 351 353 354 355 356 357 358 359 362 363 364 365 366
 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 386 387
 388 390 391 395 396 397 398 400 401 402 403 404 406 407 408 410 411 413
 414 415 416 417 418 419 421 422 423 424 425 426 431 433 434 435 436 438
 440 441 442 445 446 447 449 450 451 452 454 455 457 458 459 460 461 462
 464 465 466 467 468 469 471 474 475 476 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 523
 524 525 526 527 528 531 532 535 537 538 539 540 541 542 543 544 545 546
 549 550 551 553 554 555 556 557 558 559 561 562 563 564 565 566 567 568
 569 570 572 573 574 575 576 577 578 579 582 583 584 585 586 587 589 590
 591 592 593 595 596 597 598 599 600 602 603 605 607 609 611 612 613 614
 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 631 632 633
 634 636 640 641 642 643 644 646 647 648 649 650 652 653 654 655 656 658
 659 660 661 662 663 664 665 666 667 668 669 671 672 674 677 678 679 680
 681 682 683 684 685 687 689 690 691 692 693 694 695 696 697 698 699 700
 701 702 703 704 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 723 726 728 729 731 732 733 736 737 738 739 740 743 747 748 749 751
 753 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771
 772 773 774 775 776 777 778 779 780 781 783 784 785 786 787 788 789 790
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 808 809 810
 811 812 814 815 817 818 819 820 821 822 823 824 825 826 828 829 830 832
 833 834 835 837 838 839 840 841 843 845 846 847 848 849 850 853 854 855
 857 858 859 860 861 862 863 864 865 867 868 870 871 872 873 874 876 877
 878 879 881 882 886 887 888 889 894 895 896 897 898 899 900 901 902 905
 906 907 908 910 911 912 913 914 916 917 918 919 924 931 932 933 934 935
 936 937 938 939 940 941 942 943 945 946 947 948 951 952] are constant.

In [101]:
X_level3=X_level3[new_features_f]

param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level3, y_level3)
print(clf.best_params_)

{'penalty': 'l1', 'C': 1}

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X_level3, y_level3, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 10000)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                           _____________________Prediction_____________________
                            Common Use Video Cameras Professional Video Cameras
  Common Use Video Cameras                         2                          5
Professional Video Cameras                         1                          8

Accuracy Score:
0.625
()
Classification Report:
                            precision    recall  f1-score   support

  Common Use Video Cameras       0.67      0.29      0.40         7
Professional Video Cameras       0.62      0.89      0.73         9

               avg / total       0.64      0.62      0.58        16

In [103]:
X_all=model3[new_features_f]
target_prediction = logreg.predict(X_all)
model3['prediction_level3_traditionalvideo']=target_prediction
model3['proba_level3_traditionalvideo_prof']=logreg.predict_proba(X_all)[:,1]
model3['proba_level3_traditionalvideo_com']=logreg.predict_proba(X_all)[:,0]

In [104]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1000)
target_prediction = cross_val_predict(logreg, X_level3, y_level3, cv=cv)
level3_train['prediction_level3']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

##### 2. Action Video Cameras

In [105]:
#prediction_level2_camcorders
level3_train_actioncameras=level2_train[level2_train['Parent_node_2']=='Action Cameras']

In [106]:
level3_train_actioncameras.head()

,ID,price,360fly_x,6Ave,Air Hogs,AmazingForLess,Axess Products,Bell+Howell,BlackMagic,Blackmagic,...,zink,zoom,zoomlens,zr10,zs100,Parent_node_1,Parent_node_2,Leaf_Node,prediction_level1,prediction_level2
29,jessops-e459dfc3f0e983f1a5153c64cf6c9dd0,189.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,Cam Corders,Action Cameras,360 Degree Cameras,Cam Corders,Action Cameras
30,jessops-1f205970ab6aa5842172a4a43fdbadba,189.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,Cam Corders,Action Cameras,360 Degree Cameras,Cam Corders,Action Cameras
38,jessops-18694f9d01976d75579f280d13df4ff5,299.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,Cam Corders,Action Cameras,Non 360 Degree Cameras,Cam Corders,Action Cameras
39,jessops-e63dc708d96de0a702a08fc2fc931b1f,99.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,Cam Corders,Action Cameras,Non 360 Degree Cameras,Cam Corders,Action Cameras
40,jessops-1cc85958d3e31c96f4c3bb05794cd7b7,649.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,Cam Corders,Action Cameras,360 Degree Cameras,Cam Corders,Action Cameras

In [107]:
X_level3_ac=level3_train_actioncameras.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1','prediction_level2'],axis=1)
y_level3_ac=level3_train_actioncameras['Leaf_Node']

In [108]:
#F_CLASSIF
feature_names = list(X_level3_ac.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level3_ac, y_level3_ac)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  2   6   7   8   9  10  11  12  13  19  20  21  22  23  24  26  27  28
  29  30  32  33  34  36  38  39  40  41  43  44  46  49  50  51  52  54
  56  57  58  59  60  63  64  66  68  69  70  72  78  79  80  81  82  83
  85  86  87  88  90  91  92  93  94  95  96  97  98  99 100 102 103 104
 105 106 107 108 109 110 111 112 113 114 115 116 118 119 120 121 122 123
 124 125 126 127 130 131 132 133 134 136 137 138 139 140 141 142 143 146
 147 148 149 150 152 153 154 156 157 158 160 161 163 166 167 168 169 171
 173 174 175 176 177 178 180 181 182 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 226 227 228 229 230
 231 232 233 234 235 236 237 239 240 241 242 243 244 245 246 247 248 249
 250 251 252 253 254 255 260 264 266 267 268 270 271 274 277 279 281 282
 283 284 285 286 287 288 289 292 293 294 295 296 298 299 301 302 303 304
 308 309 311 312 313 314 315 316 317 319 320 323 327 328 329 330 331 334
 335 336 337 338 342 343 344 345 346 348 349 351 352 354 355 356 357 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 388 389 391 393 394 397 398 399 401 402 403 404
 406 407 409 410 412 413 414 415 417 418 420 421 422 424 425 426 427 428
 429 430 432 433 434 435 436 438 439 441 442 443 444 445 447 448 452 453
 454 455 456 457 462 463 465 466 467 468 469 470 471 473 475 476 477 478
 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496
 497 498 499 500 502 503 504 505 506 507 511 512 516 520 521 522 523 524
 529 530 532 533 538 546 547 548 550 551 552 553 555 556 557 558 559 560
 561 563 564 565 566 567 568 570 573 575 576 578 579 580 581 582 583 584
 585 588 589 592 593 596 597 600 601 602 604 605 607 608 609 610 611 615
 616 617 618 619 620 621 624 625 626 627 628 630 631 632 634 635 636 637
 638 640 641 642 643 644 645 646 647 649 651 652 655 656 657 658 659 660
 662 663 664 667 668 671 673 675 677 679 682 684 686 691 692 693 694 695
 696 697 700 702 703 705 706 707 708 709 710 712 714 715 716 717 718 719
 721 722 725 728 729 730 731 732 733 734 735 737 738 739 740 741 742 743
 744 745 746 747 748 750 751 752 753 757 759 761 763 764 765 766 767 768
 769 770 772 776 777 778 779 780 782 785 786 787 788 789 790 791 792 795
 796 797 798 799 800 802 803 804 805 806 811 814 815 816 817 821 824 826
 827 831 832 833 834 835 836 837 838 839 840 841 842 843 845 847 848 850
 851 853 854 855 857 858 859 860 862 863 864 866 867 868 869 871 872 873
 874 875 876 877 878 880 881 882 883 884 886 887 890 891 893 894 895 896
 897 898 903 905 908 910 911 913 914 915 916 917 918 920 921 922 923 924
 925 926 927 928 929 930 931 934 935 941 944 945 946 947 948 950 951 952] are constant.

In [109]:
X_level3_ac=X_level3_ac[new_features_f]
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level3_ac, y_level3_ac)
print(clf.best_params_)

{'penalty': 'l2', 'C': 1}

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X_level3_ac, y_level3_ac, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 10000)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                       ____________________________Prediction____________________________
                          360 Degree Cameras                  Drone Non 360 Degree Cameras
    360 Degree Cameras                     8                      0                      0
                 Drone                     0                      5                      0
Non 360 Degree Cameras                     1                      0                      4

Accuracy Score:
0.944444444444
()
Classification Report:
                        precision    recall  f1-score   support

    360 Degree Cameras       0.89      1.00      0.94         8
                 Drone       1.00      1.00      1.00         5
Non 360 Degree Cameras       1.00      0.80      0.89         5

           avg / total       0.95      0.94      0.94        18

In [111]:
X_all=model3[new_features_f2]
target_prediction = logreg.predict(X_all)
model3['prediction_level3_actionvideo']=target_prediction
logreg.predict_proba(X_all)

array([[  2.36874400e-04,   9.51600471e-01,   4.81626549e-02],
       [  3.13944725e-03,   6.89526895e-01,   3.07333657e-01],
       [  5.04290592e-04,   8.17337398e-01,   1.82158311e-01],
       ...,
       [  8.54273186e-03,   9.85946512e-01,   5.51075578e-03],
       [  7.26121431e-01,   1.11425554e-01,   1.62453014e-01],
       [  1.61381382e-03,   9.71615303e-01,   2.67708831e-02]])

In [112]:
cols=list(model3.columns.values)
import difflib
difflib.get_close_matches('sj400',cols)

[u'sj4000', u's400', u'sx400']

In [113]:
new_features_f2=['sj4000' if x=='sj400' else x for x in new_features_f]

In [114]:
X_all=model3[new_features_f2]
target_prediction = logreg.predict(X_all)
model3['prediction_level3_actionvideo']=target_prediction
model3['proba_level3_actionvideo_360deg']=logreg.predict_proba(X_all)[:,0]
model3['proba_level3_actionvideo_drone']=logreg.predict_proba(X_all)[:,1]
model3['proba_level3_actionvideo_non360']=logreg.predict_proba(X_all)[:,2]

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/linear_model/base.py:340: RuntimeWarning:

overflow encountered in exp

In [115]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1000)
target_prediction = cross_val_predict(logreg, X_level3_ac, y_level3_ac, cv=cv)
level3_train_actioncameras['prediction_level3']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

### Cameras

In [116]:
level2_train_cam=model2[model2['Parent_node_1']=='Photo Devices']

In [117]:
level2_train_cam.head()

,ID,price,360fly_x,6Ave,Air Hogs,AmazingForLess,Axess Products,Bell+Howell,BlackMagic,Blackmagic,...,zero,zink,zoom,zoomlens,zr10,zs100,Parent_node_1,Parent_node_2,Leaf_Node,prediction_level1
0,jessops-f2dd233dd6100c900432fd2902df8cde,479.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,Point & Shoot Cameras,Bridge Cameras,Photo Devices
1,jessops-ff2be7ba459709194635812c728a17fd,539.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,DSLR,DSLR,Photo Devices
2,jessops-acfa4e6fdc0962be2da5bc1ed8d44357,3249.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,DSLR,DSLR,Photo Devices
3,jessops-cabb446087d8428bfa741078869439b8,1349.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Photo Devices,DSLR,DSLR,Photo Devices
4,jessops-8c6e0672aa9297ee8ff4d95fa5e2edc0,449.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,Photo Devices,Mirrorless Cameras,Full Frame Mirrorless Camera,Photo Devices

In [118]:
X_level2_cam=level2_train_cam.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1'],axis=1)
y_level2_cam=level2_train_cam['Parent_node_2']

In [119]:
#F_CLASSIF
feature_names = list(X_level2_cam.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level2_cam, y_level2_cam)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  1   3   4   5   7   8   9  14  15  16  17  18  20  24  25  31  33  35
  36  42  47  52  53  55  57  61  62  63  71  72  73  74  75  79  80  84
  86  88  93 107 117 125 129 135 144 145 151 153 155 156 160 165 166 168
 169 170 172 179 184 198 212 219 222 225 227 229 238 255 256 258 259 260
 261 262 263 269 273 276 277 278 280 281 282 286 287 288 289 290 291 296
 305 308 320 321 324 327 329 333 336 337 339 340 341 343 349 350 353 354
 356 358 359 360 361 363 365 367 374 383 384 385 386 389 390 393 395 396
 399 400 405 408 409 412 416 422 423 428 429 431 432 437 440 446 448 449
 450 451 452 454 458 459 460 461 464 470 474 477 492 501 508 509 510 512
 513 514 517 519 522 525 526 527 528 529 530 531 533 536 537 539 540 541
 542 543 544 545 549 550 551 554 560 562 569 577 586 587 588 589 590 591
 598 602 603 604 608 613 614 622 623 629 630 638 645 650 651 653 654 655
 657 665 666 669 674 678 680 681 684 685 687 688 689 690 698 699 705 706
 710 713 722 723 724 725 726 727 728 730 731 734 735 736 739 741 742 744
 745 746 752 758 760 762 773 778 782 783 784 785 791 794 797 801 808 809
 810 812 813 816 817 818 819 820 822 826 827 829 830 846 848 851 852 854
 855 860 861 865 869 870 871 874 875 879 880 882 883 884 888 889 893 899
 901 907 912 915 919 920 921 922 923 925 926 927 929 930 932 933 936 937
 938 939 940 943 944 950] are constant.

In [120]:
X_level2_cam=X_level2_cam[new_features_f]
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level2_cam, y_level2_cam)
print(clf.best_params_)

{'penalty': 'l2', 'C': 1}

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X_level2_cam, y_level2_cam, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                      __________________________Prediction___________________________
                                      DSLR    Mirrorless Cameras Point & Shoot Cameras
                 DSLR                   16                     1                     3
   Mirrorless Cameras                    1                    22                     4
Point & Shoot Cameras                    0                     1                    38

Accuracy Score:
0.883720930233
()
Classification Report:
                       precision    recall  f1-score   support

                 DSLR       0.94      0.80      0.86        20
   Mirrorless Cameras       0.92      0.81      0.86        27
Point & Shoot Cameras       0.84      0.97      0.90        39

          avg / total       0.89      0.88      0.88        86

In [122]:
X_all=model3[new_features_f]
target_prediction = logreg.predict(X_all)
model3['prediction_level2_cameras']=target_prediction
model3['proba_level2_cameras_mirror']=logreg.predict_proba(X_all)[:,1]
model3['proba_level2_cameras_dslr']=logreg.predict_proba(X_all)[:,0]
model3['proba_level2_cameras_cam']=logreg.predict_proba(X_all)[:,2]

In [123]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1)
target_prediction = cross_val_predict(logreg, X_level2_cam, y_level2_cam, cv=cv)
level2_train_cam['prediction_level2']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

#### 1. Point & Shoot Cameras

In [124]:
#prediction_level2_camcorders
level3_train_pocam=level2_train_cam[level2_train_cam['Parent_node_2']=='Point & Shoot Cameras']

In [125]:
X_level3_po=level3_train_pocam.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1','prediction_level2'],axis=1)
y_level3_po=level3_train_pocam['Leaf_Node']

In [126]:
#F_CLASSIF
feature_names = list(X_level3_po.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level3_po, y_level3_po)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  1   2   3   4   5   7   8   9  14  15  16  17  18  19  20  21  24  25
  26  31  33  35  36  41  42  44  46  47  52  53  54  55  57  61  62  63
  69  71  72  73  74  75  78  79  80  81  83  84  85  86  87  88  92  93
  94  98  99 100 101 103 104 105 106 107 110 111 114 117 122 125 126 127
 129 130 131 132 135 136 137 138 139 141 142 143 144 145 147 151 152 153
 154 155 156 157 160 161 162 165 166 167 168 169 170 172 177 178 179 180
 181 182 184 185 189 190 191 193 194 195 196 197 198 200 202 203 205 206
 208 210 211 212 214 215 216 218 219 220 221 222 225 226 227 228 229 230
 233 234 237 238 241 243 244 245 246 247 248 249 250 251 252 255 256 258
 259 260 261 262 263 264 265 266 268 269 270 273 274 275 276 277 278 280
 281 282 284 286 287 288 289 290 291 296 303 305 308 311 316 320 321 323
 324 325 327 329 331 333 336 337 339 340 341 342 343 344 345 348 349 350
 353 354 356 358 359 360 361 363 364 365 366 367 368 369 371 372 374 375
 376 377 378 379 380 383 384 385 386 388 389 390 393 395 396 399 400 404
 405 406 408 409 410 412 414 415 416 418 419 420 421 422 423 424 426 427
 428 429 431 432 433 434 436 437 438 440 442 443 446 447 448 449 450 451
 452 454 458 459 460 461 462 463 464 467 470 474 475 476 477 492 493 496
 497 501 503 504 505 506 507 508 509 510 511 512 513 514 516 517 518 519
 520 521 522 523 525 526 527 528 529 530 531 532 533 536 537 539 540 541
 542 543 544 545 547 549 550 551 554 560 562 564 567 568 569 573 577 580
 581 585 586 587 588 589 590 591 598 600 602 603 604 607 608 610 611 612
 613 614 620 621 622 623 624 626 627 629 630 631 636 637 638 640 641 642
 644 645 646 649 650 651 653 654 655 656 657 658 662 664 665 666 667 668
 669 671 673 674 678 679 680 681 684 685 687 688 689 690 693 694 696 698
 699 705 706 707 708 710 713 714 720 721 722 723 724 725 726 727 728 729
 730 731 734 735 736 739 740 741 742 743 744 745 746 748 750 751 752 756
 758 759 760 762 765 766 772 773 775 776 778 779 780 782 783 784 785 787
 791 794 795 796 797 798 800 801 802 808 809 810 812 813 816 817 818 819
 820 822 824 826 827 828 829 830 837 838 839 840 843 846 847 848 850 851
 852 853 854 855 860 861 865 869 870 871 873 874 875 877 878 879 880 881
 882 883 884 886 887 888 889 891 892 893 898 899 901 904 907 911 912 915
 917 918 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 936
 937 938 939 940 941 943 944 946 950] are constant.

In [127]:
X_level3_po=X_level3_po[new_features_f]
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level3_po, y_level3_po)
print(clf.best_params_)

{'penalty': 'l1', 'C': 1}

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X_level3_po, y_level3_po, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                        _____________________________Prediction______________________________
                                Bridge Cameras Digital Compact Cameras                 Instant
         Bridge Cameras                     12                       5                       0
Digital Compact Cameras                      1                      16                       0
                Instant                      0                       0                       6

Accuracy Score:
0.85
()
Classification Report:
                         precision    recall  f1-score   support

         Bridge Cameras       0.92      0.71      0.80        17
Digital Compact Cameras       0.76      0.94      0.84        17
                Instant       1.00      1.00      1.00         6

            avg / total       0.87      0.85      0.85        40

In [129]:
cols=list(model3.columns.values)
import difflib
bb=difflib.get_close_matches('Instax',cols)[0]

In [130]:
difflib.get_close_matches('Instax',cols)[0]

"'Instax'"

In [131]:
new_features_f2[5]=bb

In [132]:
X_all=model3[new_features_f2]
target_prediction = logreg.predict(X_all)
model3['prediction_level3_po']=target_prediction
model3['proba_level3_po_digicompa']=logreg.predict_proba(X_all)[:,1]
model3['proba_level3_po_bridge']=logreg.predict_proba(X_all)[:,0]
model3['proba_level3_po_instant']=logreg.predict_proba(X_all)[:,2]

In [133]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l1', C= 1)
target_prediction = cross_val_predict(logreg, X_level3_po, y_level3_po, cv=cv)
level3_train_pocam['prediction_level3']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

#### 2. Mirrorless Cameras

In [134]:
#prediction_level2_camcorders
level3_train_miror=level2_train_cam[level2_train_cam['Parent_node_2']=='Mirrorless Cameras']

In [135]:
X_level3_mi=level3_train_miror.drop(['ID','Parent_node_1','Parent_node_2','Leaf_Node','prediction_level1','prediction_level2'],axis=1)
y_level3_mi=level3_train_miror['Leaf_Node']

In [136]:
#F_CLASSIF
feature_names = list(X_level3_mi.columns.values)
X_new = SelectKBest(f_classif, k=100).fit(X_level3_mi, y_level3_mi)
mask = X_new.get_support() #list of booleans
new_features_f = [] # The list of your K best features

for bool, feature in zip(mask, feature_names):
    if bool:
        new_features_f.append(feature)

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning:

Features [  1   3   4   5   6   7   8   9  10  12  13  14  15  16  17  18  20  24
  25  27  28  29  30  31  32  33  34  35  36  37  38  40  41  42  43  44
  47  50  52  53  54  55  56  57  58  59  60  61  62  63  66  68  69  70
  71  72  73  74  75  78  79  80  81  84  86  87  88  89  90  91  92  93
  95  96  98 100 101 102 103 104 106 107 109 113 114 115 116 117 119 120
 121 123 124 125 127 129 131 132 133 134 135 137 139 142 143 144 145 146
 148 149 150 151 153 154 155 156 158 160 163 164 165 166 167 168 169 170
 172 173 175 176 177 179 182 184 185 186 187 192 196 197 198 199 201 204
 205 206 208 209 210 211 212 213 217 219 220 221 222 223 224 225 226 227
 228 229 230 231 232 233 234 235 236 238 239 240 242 247 249 250 253 254
 255 256 258 259 260 261 262 263 264 266 267 269 271 273 275 276 277 278
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 298
 299 300 303 304 305 306 308 309 310 312 314 315 317 319 320 321 322 324
 325 327 329 331 333 334 335 336 337 339 340 341 343 344 346 348 349 350
 351 353 354 355 356 358 359 360 361 362 363 364 365 366 367 368 369 370
 371 372 373 374 375 376 377 378 379 380 382 383 384 385 386 389 390 391
 393 395 396 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412
 413 414 416 417 418 419 421 422 423 425 426 428 429 431 432 435 436 437
 440 441 442 445 446 448 449 450 451 452 454 455 456 457 458 459 460 461
 464 465 466 467 469 470 473 474 475 476 477 478 479 480 481 482 483 484
 485 486 487 488 489 490 491 492 495 498 499 500 501 502 507 508 509 510
 511 512 513 514 515 517 518 519 522 524 525 526 527 528 529 530 531 533
 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552
 553 554 555 556 557 558 559 560 561 562 563 564 569 570 572 573 575 576
 577 578 579 583 584 586 587 588 589 590 591 592 593 595 596 597 598 599
 601 602 603 604 608 609 610 611 613 614 616 617 619 622 623 625 629 630
 632 634 636 638 639 640 645 647 650 651 653 654 655 657 659 663 665 666
 669 672 674 676 677 678 680 681 682 683 684 685 687 688 689 690 691 692
 693 696 697 698 699 700 701 702 703 704 705 706 709 710 711 712 713 716
 717 718 719 722 723 724 725 726 727 728 730 731 732 733 734 735 736 737
 738 739 741 742 743 744 745 746 747 749 750 751 752 753 755 756 757 758
 760 761 762 763 764 765 766 767 768 769 770 773 774 775 776 777 778 779
 781 782 783 784 785 786 788 789 790 791 792 794 796 797 798 799 800 801
 802 803 804 805 806 808 809 810 811 812 813 814 815 816 817 818 819 820
 821 822 823 826 827 829 830 831 832 834 835 840 841 842 844 845 846 848
 849 851 852 853 854 855 857 858 860 861 862 863 864 865 866 867 868 869
 870 871 872 873 874 875 876 879 880 881 882 883 884 886 888 889 890 891
 893 894 895 896 897 899 900 901 904 905 906 907 908 910 912 913 914 915
 916 918 919 920 921 922 923 925 926 927 929 930 932 933 934 935 936 937
 938 939 940 941 942 943 944 945 947 948 950 951 952] are constant.

In [137]:
X_level3_mi=X_level3_mi[new_features_f]
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              "penalty": ['l2', 'l1']}
clf = GridSearchCV(linear_model.LogisticRegression(), param_grid, cv=5)
clf.fit(X_level3_mi, y_level3_mi)
print(clf.best_params_)

{'penalty': 'l2', 'C': 1}

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X_level3_mi, y_level3_mi, test_size=0.30, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1)
logreg.fit(X_train,y_train)
predictions = logreg.predict(X_test)
analytics(y_test,predictions) #real value vs. predicted values

Confusion Matrix:
                             _______________________Prediction_______________________
                            Full Frame Mirrorless Camera NonFullFrameMirrorlessCamera
Full Frame Mirrorless Camera                          10                            0
NonFullFrameMirrorlessCamera                           1                           14

Accuracy Score:
0.96
()
Classification Report:
                              precision    recall  f1-score   support

Full Frame Mirrorless Camera       0.91      1.00      0.95        10
NonFullFrameMirrorlessCamera       1.00      0.93      0.97        15

                 avg / total       0.96      0.96      0.96        25

In [139]:
X_all=model3[new_features_f]
target_prediction = logreg.predict(X_all)
model3['prediction_level3_mi']=target_prediction
model3['proba_level3_mi_nonful']=logreg.predict_proba(X_all)[:,1]
model3['proba_level3_mi_ful']=logreg.predict_proba(X_all)[:,0]

In [140]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = linear_model.LogisticRegression(penalty= 'l2', C= 1)
target_prediction = cross_val_predict(logreg, X_level3_mi, y_level3_mi, cv=cv)
level3_train_miror['prediction_level3']=target_prediction

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

### COMBINING ALL

In [141]:
level3_dslr=level2_train_cam[level2_train_cam['Parent_node_2']=='DSLR']
level3_dslr['prediction_level3']=level3_dslr['prediction_level2']

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [142]:
level3_nocamera=model2[model2['Parent_node_1']=='Not Camera']
level3_nocamera['prediction_level2']=level3_nocamera['prediction_level1']
level3_nocamera['prediction_level3']=level3_nocamera['prediction_level1']

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [143]:
all_concat=pd.concat([level3_dslr,level3_nocamera,level3_train_miror,level3_train_pocam,level3_train_actioncameras,level3_train])

In [144]:
all_concat.Parent_node_1.unique()

array([u'Photo Devices', u'Not Camera', u'Cam Corders'], dtype=object)

In [145]:
all_concat.Parent_node_2.unique()

array([u'DSLR', u'Not Camera', u'Mirrorless Cameras',
       u'Point & Shoot Cameras', u'Action Cameras',
       u'Traditional Video Cameras'], dtype=object)

In [146]:
all_concat.Leaf_Node.unique()

array([u'DSLR', u'Not Camera', u'Full Frame Mirrorless Camera',
       u'NonFullFrameMirrorlessCamera', u'Bridge Cameras',
       u'Digital Compact Cameras', u'Instant', u'360 Degree Cameras',
       u'Non 360 Degree Cameras', u'Drone', u'Common Use Video Cameras',
       u'Professional Video Cameras'], dtype=object)

In [147]:
all_concat.prediction_level1.unique()

array([u'Photo Devices', u'Cam Corders', u'Not Camera'], dtype=object)

In [148]:
all_concat.prediction_level2.unique()

array([u'DSLR', u'Point & Shoot Cameras', u'Mirrorless Cameras',
       u'Not Camera', u'Cam Corders', u'Photo Devices', u'Action Cameras',
       u'Traditional Video Cameras'], dtype=object)

In [149]:
all_concat.prediction_level3.unique()

array([u'DSLR', u'Point & Shoot Cameras', u'Mirrorless Cameras',
       u'Not Camera', u'Cam Corders', u'Photo Devices',
       u'Full Frame Mirrorless Camera', u'NonFullFrameMirrorlessCamera',
       u'Bridge Cameras', u'Digital Compact Cameras', u'Instant',
       u'360 Degree Cameras', u'Non 360 Degree Cameras', u'Drone',
       u'Common Use Video Cameras', u'Professional Video Cameras'], dtype=object)

In [150]:
all_concat.shape

(416, 960)

### For whole leaf nodes:

In [151]:
analytics(all_concat['Parent_node_1'],all_concat['prediction_level1'])#y_level3_mi,target_prediction

Confusion Matrix:
              ______________Prediction_______________
               Cam Corders    Not Camera Photo Devices
  Cam Corders           95             1            15
   Not Camera            6             9             4
Photo Devices            7             0           279

Accuracy Score:
0.920673076923
()
Classification Report:
               precision    recall  f1-score   support

  Cam Corders       0.88      0.86      0.87       111
   Not Camera       0.90      0.47      0.62        19
Photo Devices       0.94      0.98      0.96       286

  avg / total       0.92      0.92      0.92       416

In [152]:
analytics(all_concat['Parent_node_2'],all_concat['prediction_level2'])#y_level3_mi,target_prediction

Confusion Matrix:
                          _______________________________________________________________________________________________Prediction_______________________________________________________________________________________________
                                    Action Cameras               Cam Corders                      DSLR        Mirrorless Cameras                Not Camera             Photo Devices     Point & Shoot Cameras Traditional Video Cameras
           Action Cameras                       56                         0                         0                         0                         0                         0                         0                         2
              Cam Corders                        0                         0                         0                         0                         0                         0                         0                         0
                     DSLR                        0                         0                        62                         5                         0                         0                         5                         0
       Mirrorless Cameras                        0                         0                         3                        64                         0                         0                        14                         0
               Not Camera                        0                         6                         0                         0                         9                         4                         0                         0
            Photo Devices                        0                         0                         0                         0                         0                         0                         0                         0
    Point & Shoot Cameras                        0                         0                         0                         2                         0                         0                       131                         0
Traditional Video Cameras                        2                         0                         0                         0                         0                         0                         0                        51

Accuracy Score:
0.896634615385
()
Classification Report:
                           precision    recall  f1-score   support

           Action Cameras       0.97      0.97      0.97        58
              Cam Corders       0.00      0.00      0.00         0
                     DSLR       0.95      0.86      0.91        72
       Mirrorless Cameras       0.90      0.79      0.84        81
               Not Camera       1.00      0.47      0.64        19
            Photo Devices       0.00      0.00      0.00         0
    Point & Shoot Cameras       0.87      0.98      0.93       133
Traditional Video Cameras       0.96      0.96      0.96        53

              avg / total       0.92      0.90      0.90       416

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.

In [153]:
all_concat.groupby(['Leaf_Node', 'prediction_level3'])['ID'].count()

Leaf_Node                     prediction_level3
360 Degree Cameras            360 Degree Cameras              19
                              Non 360 Degree Cameras           2
Bridge Cameras                Bridge Cameras                  43
                              Digital Compact Cameras         13
Common Use Video Cameras      Common Use Video Cameras         9
                              Professional Video Cameras      12
DSLR                          DSLR                            62
                              Mirrorless Cameras               5
                              Point & Shoot Cameras            5
Digital Compact Cameras       Bridge Cameras                  11
                              Digital Compact Cameras         47
Drone                         360 Degree Cameras               2
                              Drone                           11
                              Non 360 Degree Cameras           2
Full Frame Mirrorless Camera  Full Frame Mirrorless Camera    27
                              NonFullFrameMirrorlessCamera     4
Instant                       Bridge Cameras                   1
                              Digital Compact Cameras          3
                              Instant                         15
Non 360 Degree Cameras        360 Degree Cameras               2
                              Non 360 Degree Cameras          20
NonFullFrameMirrorlessCamera  Full Frame Mirrorless Camera     2
                              NonFullFrameMirrorlessCamera    48
Not Camera                    Cam Corders                      6
                              Not Camera                       9
                              Photo Devices                    4
Professional Video Cameras    Common Use Video Cameras         4
                              Professional Video Cameras      28
Name: ID, dtype: int64

In [154]:
analytics(all_concat['Leaf_Node'],all_concat['prediction_level3'])#y_level3_mi,target_prediction

Confusion Matrix:
                             ___________________________________________________________________________________________________________________________________________________________________________________________________________________________Prediction___________________________________________________________________________________________________________________________________________________________________________________________________________________________
                                      360 Degree Cameras               Bridge Cameras                  Cam Corders     Common Use Video Cameras                         DSLR      Digital Compact Cameras                        Drone Full Frame Mirrorless Camera                      Instant           Mirrorless Cameras       Non 360 Degree Cameras NonFullFrameMirrorlessCamera                   Not Camera                Photo Devices        Point & Shoot Cameras   Professional Video Cameras
          360 Degree Cameras                          19                            0                            0                            0                            0                            0                            0                            0                            0                            0                            2                            0                            0                            0                            0                            0
              Bridge Cameras                           0                           43                            0                            0                            0                           13                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
                 Cam Corders                           0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
    Common Use Video Cameras                           0                            0                            0                            9                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                           12
                        DSLR                           0                            0                            0                            0                           62                            0                            0                            0                            0                            5                            0                            0                            0                            0                            5                            0
     Digital Compact Cameras                           0                           11                            0                            0                            0                           47                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
                       Drone                           2                            0                            0                            0                            0                            0                           11                            0                            0                            0                            2                            0                            0                            0                            0                            0
Full Frame Mirrorless Camera                           0                            0                            0                            0                            0                            0                            0                           27                            0                            0                            0                            4                            0                            0                            0                            0
                     Instant                           0                            1                            0                            0                            0                            3                            0                            0                           15                            0                            0                            0                            0                            0                            0                            0
          Mirrorless Cameras                           0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
      Non 360 Degree Cameras                           2                            0                            0                            0                            0                            0                            0                            0                            0                            0                           20                            0                            0                            0                            0                            0
NonFullFrameMirrorlessCamera                           0                            0                            0                            0                            0                            0                            0                            2                            0                            0                            0                           48                            0                            0                            0                            0
                  Not Camera                           0                            0                            6                            0                            0                            0                            0                            0                            0                            0                            0                            0                            9                            4                            0                            0
               Photo Devices                           0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
       Point & Shoot Cameras                           0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0
  Professional Video Cameras                           0                            0                            0                            4                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                            0                           28

Accuracy Score:
0.8125
()
Classification Report:
                              precision    recall  f1-score   support

          360 Degree Cameras       0.83      0.90      0.86        21
              Bridge Cameras       0.78      0.77      0.77        56
                 Cam Corders       0.00      0.00      0.00         0
    Common Use Video Cameras       0.69      0.43      0.53        21
                        DSLR       1.00      0.86      0.93        72
     Digital Compact Cameras       0.75      0.81      0.78        58
                       Drone       1.00      0.73      0.85        15
Full Frame Mirrorless Camera       0.93      0.87      0.90        31
                     Instant       1.00      0.79      0.88        19
          Mirrorless Cameras       0.00      0.00      0.00         0
      Non 360 Degree Cameras       0.83      0.91      0.87        22
NonFullFrameMirrorlessCamera       0.92      0.96      0.94        50
                  Not Camera       1.00      0.47      0.64        19
               Photo Devices       0.00      0.00      0.00         0
       Point & Shoot Cameras       0.00      0.00      0.00         0
  Professional Video Cameras       0.70      0.88      0.78        32

                 avg / total       0.86      0.81      0.83       416

In [155]:
all_concat['prediction_level3'].value_counts()

Digital Compact Cameras         63
DSLR                            62
Bridge Cameras                  55
NonFullFrameMirrorlessCamera    52
Professional Video Cameras      40
Full Frame Mirrorless Camera    29
Non 360 Degree Cameras          24
360 Degree Cameras              23
Instant                         15
Common Use Video Cameras        13
Drone                           11
Not Camera                       9
Cam Corders                      6
Point & Shoot Cameras            5
Mirrorless Cameras               5
Photo Devices                    4
Name: prediction_level3, dtype: int64

This is so far is our best model. So we are going to look at the positive and negative examples

In [156]:
Good_examples=df[df['Good Examples'].isnull()==False]

In [157]:
data_goodexamples=all_concat[['ID','Leaf_Node','Parent_node_1','Parent_node_2','prediction_level1','prediction_level2','prediction_level3']].merge(Good_examples[['ID','name']],on='ID',how='inner')

In [158]:
data_goodexamples

,ID,Leaf_Node,Parent_node_1,Parent_node_2,prediction_level1,prediction_level2,prediction_level3,name
0,uniquephoto-85c2020f9650504fc43f5a58a5b4b7cc,DSLR,Photo Devices,DSLR,Photo Devices,Mirrorless Cameras,Mirrorless Cameras,Sigma SD1 Merrill 46 MP CMOS Digital Camera (B...
1,cliftoncameras-7746bccf502f7b02bd8848c9ffc33358,DSLR,Photo Devices,DSLR,Photo Devices,DSLR,DSLR,Pentax 645Z Body Camera
2,park-0ee7097b16d6c11c4a3816ec3cb10d0d,DSLR,Photo Devices,DSLR,Photo Devices,DSLR,DSLR,Pentax 645Z + smc D-FA 645 55mm f/2.8
3,park-5f14cb6e3ae2570a735a14ca8b39f7ed,DSLR,Photo Devices,DSLR,Photo Devices,DSLR,DSLR,Sony Alpha a77 Mark II Digital SLR Camera- Body
4,park-760bab1030514154f9aa4f508d4fa6aa,DSLR,Photo Devices,DSLR,Photo Devices,DSLR,DSLR,Pentax 645Z Medium Format Camera - Body
5,park-be07b2b5aabaf28bbcaff1822ca22dce,DSLR,Photo Devices,DSLR,Photo Devices,Point & Shoot Cameras,Point & Shoot Cameras,Leica S (Typ 007)
6,robertscamera-0ea670a2897900c8fd545c80c7b25014,DSLR,Photo Devices,DSLR,Photo Devices,DSLR,DSLR,Pentax K-50 with 18-55mm and 50-200mm Lenses
7,robertscamera-21877c14fa4e328c3d898a325b791fae,DSLR,Photo Devices,DSLR,Photo Devices,Mirrorless Cameras,Mirrorless Cameras,Nikon D750 Filmmaker's Kit
8,newegg-74adc56efc327fc6ca540fbec894e36b,NonFullFrameMirrorlessCamera,Photo Devices,Mirrorless Cameras,Photo Devices,Point & Shoot Cameras,NonFullFrameMirrorlessCamera,Panasonic LUMIX LX10 20.1MP Leica DC Optical Z...
9,park-5a96ded639e32dcb778cea3c568fbe4d,Full Frame Mirrorless Camera,Photo Devices,Mirrorless Cameras,Photo Devices,Mirrorless Cameras,Full Frame Mirrorless Camera,Hasselblad X1D-50c Medium Format Mirrorless Ca...
10,park-ba981adf9290549360a1d8f78e1da4ec,Full Frame Mirrorless Camera,Photo Devices,Mirrorless Cameras,Photo Devices,Point & Shoot Cameras,Full Frame Mirrorless Camera,Leica M-A (Typ 127) Silver Chrome
11,park-c87743b33b20ffeba41b0cf0742a78b4,NonFullFrameMirrorlessCamera,Photo Devices,Mirrorless Cameras,Photo Devices,Point & Shoot Cameras,NonFullFrameMirrorlessCamera,Panasonic GX7 + 14-42mm - Black
12,robertscamera-0c2735895bcff37d9721f730e4861ba0,NonFullFrameMirrorlessCamera,Photo Devices,Mirrorless Cameras,Photo Devices,Point & Shoot Cameras,NonFullFrameMirrorlessCamera,Nikon 1 J5 with 10-30mm and 30-110mm
13,robertscamera-f2ba98c1c06550290bf4cb4717b67b32,NonFullFrameMirrorlessCamera,Photo Devices,Mirrorless Cameras,Photo Devices,DSLR,NonFullFrameMirrorlessCamera,Samsung NX30 with 18-55mm Lens
14,robertscamera-ede77a7805c17c236fbf71f4731a2200,NonFullFrameMirrorlessCamera,Photo Devices,Mirrorless Cameras,Photo Devices,Point & Shoot Cameras,NonFullFrameMirrorlessCamera,Nikon 1 J5 with 10-30mm
15,cliftoncameras-39ac90617c2c2f80a42ba9e035e1cd83,Instant,Photo Devices,Point & Shoot Cameras,Cam Corders,Point & Shoot Cameras,Digital Compact Cameras,Insta 360 One
16,park-13d7870bf81303a59fdc69e87953527f,Bridge Cameras,Photo Devices,Point & Shoot Cameras,Photo Devices,Point & Shoot Cameras,Digital Compact Cameras,Sony DSC RX100 IV Compact Digital Camera
17,park-48fefe9f2e798387f1422e4895226460,Bridge Cameras,Photo Devices,Point & Shoot Cameras,Photo Devices,Point & Shoot Cameras,Bridge Cameras,Nikon Coolpix B700 Digital camera - Red
18,park-4e9ac528d704cc575b50ca649d58c51c,Bridge Cameras,Photo Devices,Point & Shoot Cameras,Photo Devices,Point & Shoot Cameras,Bridge Cameras,Sony DSC RX10 II - Refurbished
19,park-4f1f556faa7bb16ba3bc60bc2f1991b1,Bridge Cameras,Photo Devices,Point & Shoot Cameras,Photo Devices,Mirrorless Cameras,Bridge Cameras,Leica V-LUX (Typ 114)
20,park-aaf9206b27fc66622e5cdd8928e51f6e,Bridge Cameras,Photo Devices,Point & Shoot Cameras,Photo Devices,Point & Shoot Cameras,Bridge Cameras,Nikon Coolpix B500 Plum
21,cliftoncameras-1ee963efcbb54d8fa1c016c84a0400a0,Drone,Cam Corders,Action Cameras,Cam Corders,Action Cameras,Non 360 Degree Cameras,GoPro Karma Controller
22,uniquephoto-9e625578608c9434fc2557975b217f34,360 Degree Cameras,Cam Corders,Action Cameras,Cam Corders,Action Cameras,360 Degree Cameras,GoPro Fusion
23,walmart-71ce5c1c7fcfb85cd1f6d5c723c36a23,Drone,Cam Corders,Action Cameras,Photo Devices,Action Cameras,Non 360 Degree Cameras,Parrot Pf725005 Flypad
24,park-760c452da6bcae4d817c21acd165b763,360 Degree Cameras,Cam Corders,Action Cameras,Cam Corders,Action Cameras,360 Degree Cameras,360fly 4K 360 Degree Action Camera

#### Positive Examples:
- Full Frame Cameras and non full frame cameras are distuingishing good.

#### Negative Examples:
- park-13d7870bf81303a59fdc69e87953527f should be bridge cameras but assigned as digital compact cameras.
- walmart-71ce5c1c7fcfb85cd1f6d5c723c36a23 drones are hard to distuingih

# Applying to all

In [159]:
model3.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,proba_level2_cameras_mirror,proba_level2_cameras_dslr,proba_level2_cameras_cam,prediction_level3_po,proba_level3_po_digicompa,proba_level3_po_bridge,proba_level3_po_instant,prediction_level3_mi,proba_level3_mi_nonful,proba_level3_mi_ful
0,799.99,0,0,0,0,0,0,0,0,0,...,0.541819,0.264947,0.193234,Bridge Cameras,0.261888,0.608653,0.129459,NonFullFrameMirrorlessCamera,0.951185,0.048815
1,699.99,0,0,0,0,0,0,0,0,0,...,0.375178,0.251738,0.373084,Bridge Cameras,0.408964,0.480898,0.110138,NonFullFrameMirrorlessCamera,0.745571,0.254429
2,1099.95,0,0,0,0,0,0,0,0,0,...,0.207221,0.779487,0.013292,Bridge Cameras,0.175189,0.721816,0.102995,NonFullFrameMirrorlessCamera,0.707852,0.292148
3,1295.00,0,0,0,0,0,0,0,0,0,...,0.240855,0.138453,0.620693,Bridge Cameras,0.162230,0.778993,0.058777,NonFullFrameMirrorlessCamera,0.721642,0.278358
4,399.99,0,0,0,0,0,0,0,0,0,...,0.466584,0.154258,0.379158,Digital Compact Cameras,0.493350,0.364065,0.142586,NonFullFrameMirrorlessCamera,0.980038,0.019962

## Level 1

- Whether camera, camcorder or not camera

In [160]:
model3['prediction_level1'].value_counts()

Photo Devices    18833
Cam Corders       3463
Not Camera         683
Name: prediction_level1, dtype: int64

In [161]:
model3.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,proba_level2_cameras_mirror,proba_level2_cameras_dslr,proba_level2_cameras_cam,prediction_level3_po,proba_level3_po_digicompa,proba_level3_po_bridge,proba_level3_po_instant,prediction_level3_mi,proba_level3_mi_nonful,proba_level3_mi_ful
0,799.99,0,0,0,0,0,0,0,0,0,...,0.541819,0.264947,0.193234,Bridge Cameras,0.261888,0.608653,0.129459,NonFullFrameMirrorlessCamera,0.951185,0.048815
1,699.99,0,0,0,0,0,0,0,0,0,...,0.375178,0.251738,0.373084,Bridge Cameras,0.408964,0.480898,0.110138,NonFullFrameMirrorlessCamera,0.745571,0.254429
2,1099.95,0,0,0,0,0,0,0,0,0,...,0.207221,0.779487,0.013292,Bridge Cameras,0.175189,0.721816,0.102995,NonFullFrameMirrorlessCamera,0.707852,0.292148
3,1295.00,0,0,0,0,0,0,0,0,0,...,0.240855,0.138453,0.620693,Bridge Cameras,0.162230,0.778993,0.058777,NonFullFrameMirrorlessCamera,0.721642,0.278358
4,399.99,0,0,0,0,0,0,0,0,0,...,0.466584,0.154258,0.379158,Digital Compact Cameras,0.493350,0.364065,0.142586,NonFullFrameMirrorlessCamera,0.980038,0.019962

In [162]:
data_final=model3[['prediction_level1']]

In [163]:
data_final.head()

  prediction_level1
0     Photo Devices
1       Cam Corders
2     Photo Devices
3       Cam Corders
4     Photo Devices

## Level 2

- Whether traditional video cameras, action cameras, DSLR, Point & shoot cameras, mirrorless cameras or not camera

Idea: If the parent level 1 prediction is cameras then take the one with maximum probability: DSLR, Point & Shoot Cameras, Mirrorless Cameras

- Photo Devices

In [164]:
data_photos=model3[model3['prediction_level1']=='Photo Devices']
data_photos.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,proba_level2_cameras_mirror,proba_level2_cameras_dslr,proba_level2_cameras_cam,prediction_level3_po,proba_level3_po_digicompa,proba_level3_po_bridge,proba_level3_po_instant,prediction_level3_mi,proba_level3_mi_nonful,proba_level3_mi_ful
0,799.99,0,0,0,0,0,0,0,0,0,...,0.541819,0.264947,0.193234,Bridge Cameras,0.261888,0.608653,0.129459,NonFullFrameMirrorlessCamera,0.951185,0.048815
2,1099.95,0,0,0,0,0,0,0,0,0,...,0.207221,0.779487,0.013292,Bridge Cameras,0.175189,0.721816,0.102995,NonFullFrameMirrorlessCamera,0.707852,0.292148
4,399.99,0,0,0,0,0,0,0,0,0,...,0.466584,0.154258,0.379158,Digital Compact Cameras,0.493350,0.364065,0.142586,NonFullFrameMirrorlessCamera,0.980038,0.019962
5,2796.95,0,0,0,0,0,0,0,0,0,...,0.384451,0.611317,0.004233,Bridge Cameras,0.011522,0.962706,0.025772,NonFullFrameMirrorlessCamera,0.595664,0.404336
8,396.95,0,0,0,0,0,0,0,0,0,...,0.079672,0.174550,0.745778,Bridge Cameras,0.403891,0.426733,0.169376,NonFullFrameMirrorlessCamera,0.835349,0.164651

In [165]:
data=data_photos[['proba_level2_cameras_mirror','proba_level2_cameras_dslr','proba_level2_cameras_cam']]
max_values=list(data.max(axis=1))

In [166]:
data.head()

,proba_level2_cameras_mirror,proba_level2_cameras_dslr,proba_level2_cameras_cam
0,0.541819,0.264947,0.193234
2,0.207221,0.779487,0.013292
4,0.466584,0.154258,0.379158
5,0.384451,0.611317,0.004233
8,0.079672,0.174550,0.745778

In [167]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level2_cameras_mirror']==max_values[k]):
        value.append('Mirrorless Cameras')
    elif(data.loc[i]['proba_level2_cameras_dslr']==max_values[k]):
        value.append('DSLR')
    elif(data.loc[i]['proba_level2_cameras_cam']==max_values[k]):
        value.append('Point & Shoot Cameras')
    k=k+1

In [168]:
len(n)

18833

In [169]:
len(value)

18833

In [170]:
cameras=pd.DataFrame({'index':n,'level2_pred':value})

In [171]:
cameras.head()

   index            level2_pred
0      0     Mirrorless Cameras
1      2                   DSLR
2      4     Mirrorless Cameras
3      5                   DSLR
4      8  Point & Shoot Cameras

- Video Cameras

In [172]:
data_camco=model3[model3['prediction_level1']=='Cam Corders']
data_camco.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,proba_level2_cameras_mirror,proba_level2_cameras_dslr,proba_level2_cameras_cam,prediction_level3_po,proba_level3_po_digicompa,proba_level3_po_bridge,proba_level3_po_instant,prediction_level3_mi,proba_level3_mi_nonful,proba_level3_mi_ful
1,699.99,0,0,0,0,0,0,0,0,0,...,0.375178,0.251738,0.373084,Bridge Cameras,0.408964,0.480898,0.110138,NonFullFrameMirrorlessCamera,0.745571,0.254429
3,1295.00,0,0,0,0,0,0,0,0,0,...,0.240855,0.138453,0.620693,Bridge Cameras,0.162230,0.778993,0.058777,NonFullFrameMirrorlessCamera,0.721642,0.278358
6,899.99,0,0,0,0,0,0,0,0,0,...,0.307500,0.241396,0.451104,Bridge Cameras,0.199285,0.636721,0.163994,NonFullFrameMirrorlessCamera,0.591121,0.408879
7,349.99,0,0,0,0,0,0,0,0,0,...,0.165668,0.221305,0.613027,Bridge Cameras,0.268226,0.582483,0.149291,NonFullFrameMirrorlessCamera,0.780981,0.219019
11,1499.00,0,0,0,0,0,0,0,0,0,...,0.381195,0.320130,0.298674,Bridge Cameras,0.068005,0.884977,0.047019,NonFullFrameMirrorlessCamera,0.556781,0.443219

In [173]:
model3['prediction_level1'].unique

<bound method Series.unique of 0        Photo Devices
1          Cam Corders
2        Photo Devices
3          Cam Corders
4        Photo Devices
5        Photo Devices
6          Cam Corders
7          Cam Corders
8        Photo Devices
9        Photo Devices
10       Photo Devices
11         Cam Corders
12       Photo Devices
13       Photo Devices
14       Photo Devices
15       Photo Devices
16         Cam Corders
17       Photo Devices
18         Cam Corders
19       Photo Devices
20         Cam Corders
21       Photo Devices
22       Photo Devices
23       Photo Devices
24       Photo Devices
25       Photo Devices
26       Photo Devices
27       Photo Devices
28       Photo Devices
29       Photo Devices
             ...
22949    Photo Devices
22950    Photo Devices
22951    Photo Devices
22952    Photo Devices
22953      Cam Corders
22954    Photo Devices
22955    Photo Devices
22956      Cam Corders
22957    Photo Devices
22958    Photo Devices
22959    Photo Devices
22960    Photo Devices
22961    Photo Devices
22962    Photo Devices
22963    Photo Devices
22964    Photo Devices
22965    Photo Devices
22966    Photo Devices
22967    Photo Devices
22968    Photo Devices
22969      Cam Corders
22970    Photo Devices
22971    Photo Devices
22972      Cam Corders
22973    Photo Devices
22974    Photo Devices
22975    Photo Devices
22976    Photo Devices
22977    Photo Devices
22978    Photo Devices
Name: prediction_level1, Length: 22979, dtype: object>

In [174]:
data=data_camco[['proba_level2_camcorder_trad','proba_level2_camcorder_action']]
max_values=list(data.max(axis=1))

In [175]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level2_camcorder_trad']==max_values[k]):
        value.append('Traditional Video Cameras')
    else:
        value.append('Action Cameras')
    k=k+1

In [176]:
camcorders=pd.DataFrame({'index':n,'level2_pred':value})

In [177]:
camcorders.head()

   index                level2_pred
0      1  Traditional Video Cameras
1      3  Traditional Video Cameras
2      6  Traditional Video Cameras
3      7             Action Cameras
4     11  Traditional Video Cameras

In [178]:
data_final.shape

(22979, 1)

In [179]:
rest_n1=list(set(list(data_final.index))-set(list(camcorders['index']))) 
rest_n2=list(set(rest_n1)-set(cameras['index']))

In [180]:
nocameras=pd.DataFrame({'index':rest_n2,'level2_pred':'No Camera'})

In [181]:
app1=nocameras.append(camcorders)
app1=app1.append(cameras)

In [182]:
app1=app1.sort_values('index')
app1=app1.reset_index()
app1=app1.drop('level_0',axis=1)

In [183]:
app1.head()

   index                level2_pred
0      0         Mirrorless Cameras
1      1  Traditional Video Cameras
2      2                       DSLR
3      3  Traditional Video Cameras
4      4         Mirrorless Cameras

In [184]:
data_final['level_2_pred']=app1['level2_pred']
data_final.head()

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

  prediction_level1               level_2_pred
0     Photo Devices         Mirrorless Cameras
1       Cam Corders  Traditional Video Cameras
2     Photo Devices                       DSLR
3       Cam Corders  Traditional Video Cameras
4     Photo Devices         Mirrorless Cameras

In [185]:
data_final['level_2_pred'].value_counts()

Point & Shoot Cameras        8453
DSLR                         6025
Mirrorless Cameras           4355
Action Cameras               2647
Traditional Video Cameras     816
No Camera                     683
Name: level_2_pred, dtype: int64

## Level 3

- Action Cameras: Drones, 360 degree cameras, non 360 degree cameras

In [186]:
data_photos=data_final[data_final['level_2_pred']=='Action Cameras']
data_photos.shape

(2647, 2)

In [187]:
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [188]:
data_photos.shape

(2647, 9917)

In [189]:
data=data_photos[['proba_level3_actionvideo_360deg','proba_level3_actionvideo_non360','proba_level3_actionvideo_drone']]
max_values=list(data.max(axis=1))

In [190]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level3_actionvideo_360deg']==max_values[k]):
        value.append('360degree')
    if(data.loc[i]['proba_level3_actionvideo_non360']==max_values[k]):
        value.append('Non 360degree')
    if(data.loc[i]['proba_level3_actionvideo_drone']==max_values[k]):
        value.append('Drones')
    k=k+1

In [191]:
action=pd.DataFrame({'index':n,'level3_pred':value})

- Traditional Video Cameras

In [192]:
data_photos=data_final[data_final['level_2_pred']=='Traditional Video Cameras']
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [193]:
data=data_photos[['proba_level3_traditionalvideo_prof','proba_level3_traditionalvideo_com']]
max_values=list(data.max(axis=1))

In [194]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level3_traditionalvideo_prof']==max_values[k]):
        value.append('Prof Video')
    if(data.loc[i]['proba_level3_traditionalvideo_com']==max_values[k]):
        value.append('Traditional Video')
    k=k+1

In [195]:
trad=pd.DataFrame({'index':n,'level3_pred':value})

- Mirrorless Cameras

In [196]:
data_photos=data_final[data_final['level_2_pred']=='Mirrorless Cameras']
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [197]:
data=data_photos[['proba_level3_mi_nonful','proba_level3_mi_ful']]
max_values=list(data.max(axis=1))

In [198]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level3_mi_nonful']==max_values[k]):
        value.append('Non-fullFrame Mirrorless')
    if(data.loc[i]['proba_level3_mi_ful']==max_values[k]):
        value.append('FullFrame Mirrorless')
    k=k+1

In [199]:
mii=pd.DataFrame({'index':n,'level3_pred':value})

- DSLR

In [200]:
data_photos=data_final[data_final['level_2_pred']=='DSLR']
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [201]:
data_photos.head()

,price,'Canon','Fujifilm','GoPro','Instax','Kodak','Nikon','Olympus','Panasonic','Pentax',...,proba_level2_cameras_dslr,proba_level2_cameras_cam,prediction_level3_po,proba_level3_po_digicompa,proba_level3_po_bridge,proba_level3_po_instant,prediction_level3_mi,proba_level3_mi_nonful,proba_level3_mi_ful,innn
2,1099.95,0,0,0,0,0,0,0,0,0,...,0.779487,0.013292,Bridge Cameras,0.175189,0.721816,0.102995,NonFullFrameMirrorlessCamera,0.707852,0.292148,True
5,2796.95,0,0,0,0,0,0,0,0,0,...,0.611317,0.004233,Bridge Cameras,0.011522,0.962706,0.025772,NonFullFrameMirrorlessCamera,0.595664,0.404336,True
9,699.99,0,0,0,0,0,0,0,0,0,...,0.861348,0.024927,Bridge Cameras,0.382314,0.500242,0.117445,NonFullFrameMirrorlessCamera,0.914681,0.085319,True
14,2296.95,0,0,0,0,0,0,0,0,0,...,0.679996,0.092298,Bridge Cameras,0.039055,0.928337,0.032608,NonFullFrameMirrorlessCamera,0.743813,0.256187,True
15,1296.95,0,0,0,0,0,0,0,0,0,...,0.810353,0.025061,Bridge Cameras,0.199752,0.734879,0.065369,NonFullFrameMirrorlessCamera,0.873722,0.126278,True

In [202]:
dslr=pd.DataFrame({'index':list(data_photos.index),'level3_pred':'DSLR'})

- No Camera

In [203]:
data_photos=data_final[data_final['level_2_pred']=='No Camera']
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [204]:
nocamera=pd.DataFrame({'index':list(data_photos.index),'level3_pred':'No Camera'})

- Point & Shoot Cameras

In [205]:
data_photos=data_final[data_final['level_2_pred']=='Point & Shoot Cameras']
model3['innn']=model3.index.isin(list(data_photos.index))
data_photos=model3[model3['innn']== True]

In [206]:
data=data_photos[['proba_level3_po_digicompa','proba_level3_po_bridge','proba_level3_po_instant']]
max_values=list(data.max(axis=1))

In [207]:
n=list(data.index)
k=0
value=[]
for i in n:
    if(data.loc[i]['proba_level3_po_digicompa']==max_values[k]):
        value.append('Digital Compact Cameras')
    if(data.loc[i]['proba_level3_po_bridge']==max_values[k]):
        value.append('Bridge Cameras')
    if(data.loc[i]['proba_level3_po_instant']==max_values[k]):
        value.append('Instant Cameras')
    k=k+1

In [208]:
poo=pd.DataFrame({'index':n,'level3_pred':value})

- Now all pred3

In [209]:
app1=trad.append([poo,dslr,mii,nocamera,dslr,action])

In [210]:
app1=app1.sort_values('index')
app1=app1.drop_duplicates() 
app1=app1.reset_index()
app1=app1.drop('level_0',axis=1)

In [211]:
app1.head()

   index               level3_pred
0      0  Non-fullFrame Mirrorless
1      1         Traditional Video
2      2                      DSLR
3      3                Prof Video
4      4  Non-fullFrame Mirrorless

In [212]:
app1.shape

(22979, 2)

In [213]:
data_final['level3_pred']=app1['level3_pred']

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [214]:
data_final.head()

  prediction_level1               level_2_pred               level3_pred
0     Photo Devices         Mirrorless Cameras  Non-fullFrame Mirrorless
1       Cam Corders  Traditional Video Cameras         Traditional Video
2     Photo Devices                       DSLR                      DSLR
3       Cam Corders  Traditional Video Cameras                Prof Video
4     Photo Devices         Mirrorless Cameras  Non-fullFrame Mirrorless

In [215]:
data_final['level3_pred'].value_counts()

Digital Compact Cameras     7301
DSLR                        6025
Non-fullFrame Mirrorless    3518
Non 360degree               2204
Bridge Cameras               951
FullFrame Mirrorless         837
No Camera                    683
Traditional Video            433
Prof Video                   383
360degree                    258
Instant Cameras              201
Drones                       185
Name: level3_pred, dtype: int64

In [216]:
data_final.head()

  prediction_level1               level_2_pred               level3_pred
0     Photo Devices         Mirrorless Cameras  Non-fullFrame Mirrorless
1       Cam Corders  Traditional Video Cameras         Traditional Video
2     Photo Devices                       DSLR                      DSLR
3       Cam Corders  Traditional Video Cameras                Prof Video
4     Photo Devices         Mirrorless Cameras  Non-fullFrame Mirrorless

In [217]:
model3.shape

(22979, 9917)

In [218]:
data_final.shape

(22979, 3)

In [219]:
data_final['id']=a2['identifier']
data_final['brand']=a2['brand']
data_final['name']=a2['name']
data_final['price']=price_df['price_f']

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/bengikoseoglu/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [220]:
data_final.head()

,prediction_level1,level_2_pred,level3_pred,id,brand,name,price
0,Photo Devices,Mirrorless Cameras,Non-fullFrame Mirrorless,robertscamera-008a7f761a7996836c0dd575f1760ab6,Panasonic,Panasonic \t\tLumix DMC-GX7 (Body Only),799.99
1,Cam Corders,Traditional Video Cameras,Traditional Video,robertscamera-03544e86402ebfdfb82e3a1b87ac1c9b,Sony,Sony \t\tHDR-PJ670 Camcorder with Built-in Pro...,699.99
2,Photo Devices,DSLR,DSLR,robertscamera-03ddd653bb4422f0a040a458a770a5cf,Pentax,Pentax \t\tKP (Body Only),1099.95
3,Cam Corders,Traditional Video Cameras,Prof Video,robertscamera-0482c11ee587a6b78530b61fdffd77a0,Blackmagic Design,Blackmagic Design \t\tMicro Studio Camera 4K,1295.00
4,Photo Devices,Mirrorless Cameras,Non-fullFrame Mirrorless,robertscamera-06533827a6d5aeba91b984cb079d555e,Olympus,Olympus \t\tPEN E-PL5 with 14-42mm,399.99

In [221]:
import os
os.chdir('/Users/bengikoseoglu/Documents/Masters/Semester2/TeamProject/Product_Classification/Deliverables/Deliverable-Phase3/Cameras')

In [222]:
data_final.to_csv('PHASE4_CAMERA_CLASSIFICATION.csv')